const express = require('express')
const app = express()
const morgan = require('morgan')
const path = require('path')
const userRouter = require('../express/routes/userRoute')    
const connection = require('../database/connection')